# Generated by Django 2.0.6 on 2021-09-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('pk_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pk_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('pk_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('img', models.URLField(default='https://i.postimg.cc/Hk439n1v/no-found.jpg', max_length=8000)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='fk_Mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webveterinaria.Mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webveterinaria.Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_Mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webveterinaria.Mascota'),
        ),
    ]
